/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Com_Ndk_Test_JniClient */

#ifndef _Included_Com_Ndk_Test_JniClient
#define _Included_Com_Ndk_Test_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Com_Ndk_Test_JniClient
 * Method:    AddStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Com_Ndk_Test_JniClient_AddStr
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     Com_Ndk_Test_JniClient
 * Method:    AddInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Com_Ndk_Test_JniClient_AddInt
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
